AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: github-codepipeline-app

# This is just here as an example resource
Globals:
  Function:
    Timeout: 10
    
Resources:
  ApplicationBucket:
    Type: AWS::S3::Bucket
    
  CodepipelineLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./CodepipelineLambda/CodepipelineLambda/
      Handler: CodepipelineLambda::CodepipelineLambda.Function::FunctionHandler
      Runtime: dotnetcore2.1
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Test:
          Type: Api
          Properties:
            Path: /test
            Method: get
            
  CodepipelineLambdaRole1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess #TODO: Reduce permissions
Outputs:
  SamApi:
    Description: "API Gateway endpoint URL for test stage for an empty function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Codepipeline/test/"
  CodepipelineLambda:
    Description: "SamLambda Function ARN"
    Value: !GetAtt CodepipelineLambdaRole1.Arn
  SamLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for an empty function"
    Value: !GetAtt CodepipelineLambdaRole1.Arn
