AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: github-codepipeline-app

# This is just here as an example resource
Globals:
  Function:
    Timeout: 10
    
Resources:
  ApplicationBucket:
    Type: AWS::S3::Bucket
    
  CodepipelineLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
          Bucket: github-codepipeline-1-pipelineartifactsbucket-yrrpozcsam8b
          Key: !Sub "github-codepipeline-/SourceCode/7qbXB3U.zip"
      Handler: CodepipelineLambda::CodepipelineLambda.Function::FunctionHandler
      Runtime: dotnetcore2.1
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Test:
          Type: Api
          Properties:
            Path: /test
            Method: get

Outputs:
  SamApi:
    Description: "API Gateway endpoint URL for test stage for an empty function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Codepipeline/test/"
  CodepipelineLambda:
    Description: "SamLambda Function ARN"
    Value: !GetAtt CodepipelineLambda.Arn
  SamLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for an empty function"
    Value: !GetAtt SamLambdaFunctionRole.Arn
