version: 0.2

phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore CodepipelineLambda/CodepipelineLambda/CodepipelineLambda.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output CodepipelineLambda/CodepipelineLambda/CodepipelineLambda.csproj
artifacts:
  files:
    - CodepipelineLambda/CodepipelineLambda/CodepipelineLambda/build_output/**/*
