version: 0.2

phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore CodepipelineLambda.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output CodepipelineLambda.csproj
artifacts:
  files:
    - CodepipelineLambda/build_output/**/*
    - scripts/**/*
    - appspec.yml
