version: 0.2

phases:
  install:
    runtime-versions :
        dotnet: 2.2
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore CodepipelineLambda/CodepipelineLambda/CodepipelineLambda.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output CodepipelineLambda/CodepipelineLambda/CodepipelineLambda.csproj
      - export BUCKET=vulnerability-scan-sam
      - aws cloudformation package --template-file application.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - CodepipelineLambda/CodepipelineLambda/build_output/**/*
    - application.yaml
    - outputtemplate.yml
